import { assertProductIdl, resolveProductDir } from "./utils";

const productName = Bun.argv[2];
if (!productName) {
  throw new Error("Usage: bun src/scripts/generate-cargo-toml.ts <product-name>");
}

const productDir = resolveProductDir(productName);
const rustDir = `${productDir}/rust`;
const crateName = `jupiter-${productName}-sdk`;
const displayName = productName.charAt(0).toUpperCase() + productName.slice(1);

await assertProductIdl(productDir);

await Bun.write(
  `${rustDir}/Cargo.toml`,
  `# This file is generated by src/scripts/generate-cargo-toml.ts. Do not edit by hand.

[package]
name = "${crateName}"
version.workspace = true
description = "Jupiter ${displayName} SDK"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish = true

[lib]
path = "lib.rs"

[features]
anchor = ["dep:anchor-lang"]
anchor-idl-build = ["anchor", "anchor-lang?/idl-build"]
fetch = ["dep:solana-rpc-client"]

# Dependency set captured from Codama's rust renderer sync output
# (@codama/renderers-rust), plus num-traits (required by num_derive::FromPrimitive;
# Codama's used-deps scan omits it).
[dependencies]
borsh = "^1.0"
num-derive = "^0.4"
num-traits = "^0.2"
solana-account = "~3.0"
solana-account-info = "~3.1"
solana-cpi = "~3.1"
solana-instruction = "~3.2"
solana-program-error = "~3.0"
thiserror = "^1.0"
solana-address = { version = "~2.2", features = ["borsh", "copy", "curve25519", "decode"] }
solana-rpc-client = { version = "^3.0", optional = true }
anchor-lang = { version = "~0.31", optional = true }
`,
);
console.log(`Wrote ${rustDir}/Cargo.toml`);

const libPath = `${rustDir}/lib.rs`;
await Bun.write(
  libPath,
  `//! Generated ${productName} Rust client.

pub mod generated;

pub use generated::programs::*;
pub use generated::shared;
`,
);
console.log(`Wrote ${libPath}`);
